# Generated by Django 5.2.8 on 2025-12-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITwebapp', '0003_remove_lesson_content_lessoncontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessoncontent', to='ITwebapp.lesson'),
        ),
    ]
